### ISSUE TITLE
License

### ISSUE THREAD

**Issue by SamMousa** [ehynds/jquery-notify#16]
Hi Eric,

Could you add some licensing information for this project?

Maybe apply one of the wellknown open source licenses to it?

Cheers!

**Comment by onlyjob** [comment]
Although _MIT_ and unversioned _GPL_ license are mentioned in the [header](../blob/master/src/jquery.notify.js), it is important to add a text of the license(s) and proper copyright statement.

**Comment by SamMousa** [comment]
This project seems dead.
