### ISSUE TITLE
feature request: pooling

### ISSUE THREAD

**Issue by andriijas** [ehynds/jquery-notify#6]
Got any engery to add pooling like in jGrowl?
http://www.nilefmonline.com/lib/jGrowl-1.2.0/examples/jgrowl-pool.html

This specifies how many messages can be pooled out at any given time to a given instance
If there are more notifications raised than the pool, the others are
placed into queue and rendered after the other have disapeared.

**Comment by sgreenfield** [comment]
Pretty sure this pull request closes this issue.

https://github.com/ehynds/jquery-notify/pull/11

**Comment by ehynds** [comment]
Indeed.
